### ISSUE TITLE
TypeError: uri.match is not a function

### ISSUE THREAD

**Issue by dakolech** [Useful-Software-Solutions-Ltd/angular2-disqus#1]
I have a problem with angular2-disqus. When I include DisqusModule I have this errror:
`zone.js:260Uncaught TypeError: uri.match is not a function_split @ url_resolver.js:238getUrlScheme @ url_resolver.js:80componentModuleUrl @ metadata_resolver.js:750CompileMetadataResolver.getDirectiveMetadata @ metadata_resolver.js:155(anonymous function) @ metadata_resolver.js:267CompileMetadataResolver.getNgModuleMetadata @ metadata_resolver.js:260(anonymous function) @ metadata_resolver.js:252CompileMetadataResolver.getNgModuleMetadata @ metadata_resolver.js:239(anonymous function) @ metadata_resolver.js:252CompileMetadataResolver.getNgModuleMetadata @ metadata_resolver.js:239RuntimeCompiler._compileComponents @ runtime_compiler.js:150RuntimeCompiler._compileModuleAndComponents @ runtime_compiler.js:72RuntimeCompiler.compileModuleAsync @ runtime_compiler.js:49PlatformRef_._bootstrapModuleWithZone @ application_ref.js:368PlatformRef_.bootstrapModule @ application_ref.js:361main @ main.ts:16(anonymous function) @ main.ts:37ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256ZoneTask.invoke @ zone.js:423`

**Comment by dakolech** [comment]
And when I deleted `moduleId: module.id` then it started working

**Comment by JayChase** [comment]
I published v 2.0.1 to NPM with your fix in. Thanks again.
