### ISSUE TITLE
Unhandled Promise rejection: Zone.assertZonePatched is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Zone.assertZonePatched is not a function

### ISSUE THREAD

**Issue by larbba** [Useful-Software-Solutions-Ltd/angular2-disqus#4]
I'm trying to install angular2-disqus on plain Angular2 setup made with the angular-cli (1.0.0-beta.21) and receiving following error: 
`Unhandled Promise rejection: Zone.assertZonePatched is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Zone.assertZonePatched is not a function
`
During installation I received warnings: 
```
├── angular2-disqus@5.0.0
├── UNMET PEER DEPENDENCY rxjs@5.0.0-rc.4
└── UNMET PEER DEPENDENCY zone.js@0.7.2
```

Do I need to have some specific versions of rxjs and zone to make it work or is the module error related to something else?

**Comment by JayChase** [comment]
Hi. Sorry about the delay getting back to you. If you are still having this issue could you make sure the zone.js is on version 0.6.23 or later?

**Comment by JayChase** [comment]
Please re-test against **angular2-disqus@latest**.
