### ISSUE TITLE
comments not showing in ionic2

### ISSUE THREAD

**Issue by Brle88** [Useful-Software-Solutions-Ltd/angular2-disqus#5]
Hi, how you tried to implement this into an ionic 2 app? I've imported the module, but all I get is the 'comments powered by Disqus' link, and nothing else. There are no errors to debug missing comments. Could you please provide some help with this?

EDIT:  Just to clarify what are the page-identifiers and page-url? I've used disqus on my website, and I've had to pass two variables - disqus shortname and disqus identifier, aka slug. Are those the same thing?

Thank you

**Comment by JayChase** [comment]
I've not tried it with ionic 2 yet. The page properties are the unique identifiers for the page so that Disqus knows which comments to load see [here](https://help.disqus.com/customer/portal/articles/472107-using-disqus-on-ajax-sites) for more info.
