### ISSUE TITLE
Angular2-cli  has no exported member 'DisqusService

### ISSUE THREAD

**Issue by Ferreiramg** [Useful-Software-Solutions-Ltd/angular2-disqus#7]
``$ng serve`` -> `blog/node_modules/angular2-disqus/lib/disqus.module"' has no exported member 'DisqusService'.`

Using the default installation of angular2-cli (ng new foo). The module is not loaded.

Module import.
`import { DisqusService, DisqusThreadComponent } from '../../node_modules/angular2-disqus';`
and angular2-cli.json
```
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "packages": [
        "node_modules/angular2-disqus/lib"
      ],
```
 But, not yet success

**Comment by JayChase** [comment]
Really sorry about the delay. A new version is available to test **angular2-disqus@latest**. It has been updated for Angular 4. Also on new versions of Angular-cli you no longer need to add the package in **angular2-cli.json** just import the module.
